### ISSUE TITLE
Reference for "about 10% of Titan’s capacity remains unused"

### ISSUE THREAD

**Issue by wellsjc** [ATLAS-Titan/PanDA-WMS-paper#10]
We might consider adding a reference for our statement in Section 3.2 that "about 10% of Titan’s capacity remains unused".   This can be our most recent 2015 OLCF Operational Assessment Report.
https://www.olcf.ornl.gov/wp-content/uploads/2013/01/2015_OA_Final.pdf
This document is also available by OSTI.
See "Total Usage" in Table 2.3 on page 25 of the manuscript.  

Our new 2016 OAR is currently under review by DOE and will be GA later this year.

**Comment by wellsjc** [comment]
30,000 x86 cores represents 10% of the WLCG, not 30%, correct?   Earlier in our manuscript we state that WLCG has approximately 300,000 cores.

**Comment by mturilli** [comment]
Thank you and well spotted! Addressed by 20dbc8de7a780a3e974d17b97756caa34e49d37e
