### ISSUE TITLE
Definition of "core".

### ISSUE THREAD

**Issue by wellsjc** [ATLAS-Titan/PanDA-WMS-paper#11]
We need to be aware that our manuscript is using a definition of "core" that is the same as one x86 core. At OLCF, when we talk about "Titan core hours", we are assigning 30 "Titan cores" to each node.  The numbers I contribute and in our OAR are in "Titan core hours".   We can, of course, convert between these different definitions.

**Comment by mturilli** [comment]
My bad and probably not easy to fix before submission. I changed 'core-hours' to 'titan core-hours' and checked whether we had explicit conversions between titan core hours to number of worker nodes. Possibly, an open issue is the comparison between titan core-hours and grid core-hours. I am afraid this will have to be catalogued under 'honest mistake' for the time being.

**Comment by wellsjc** [comment]
As far as it goes, it will be easy to convert our Figure 3 to simple "core hours" and away from "Titan core hours".   All we need to do is multiply by (16/30).

**Comment by mturilli** [comment]
Right, thank you. I uploaded a new version of Figure 3 with the core hours multiplied by (16/30) and eliminated the reference to 'Titan core-hours' from the text. Does this address this issue?

**Comment by wellsjc** [comment]
Yes, from the definition of "core-hour", I think we should use the simple definition of one x86 core, ignoring the GPUs.

I think we still need to discuss which dataset of unused hours we should published.   I recommend that we use the larger numbers, and not the adjusted hours.  We should discuss today at 2pm E.
