### ISSUE TITLE
Conclusion: Section 7: "the time-averaged utilization of Titan has consistently been upwards of 90%"

### ISSUE THREAD

**Issue by wellsjc** [ATLAS-Titan/PanDA-WMS-paper#17]
The 52 Million core hours used by ATLAS, via PanDA, is over 2% of the total utilization on Titan over the same period.   So, I think we can take credit for increasing the utilization of Titan by 2%.  

This 2% effect cannot explain the difference in utilization between Titan and BlueWaters.  So, I am not sure I am comfortable with the comparison between Titan and BW.

And this 2% effect has been achieved with a workload duration of ~100 minutes or greater.  Given a broader range of workload durations, greater utilization would be achieved.

**Comment by shantenujha** [comment]
Jack -- I understand. I will remove a direct comparison with Blue Waters and introduce this in a positive way.

**Comment by shantenujha** [comment]
Jack: How does this read to you?

The 52M core hours used by ATLAS, via PanDA, is over 2% of the total utilization on Titan over the same period, bringing the time-averaged utilization of Titan to be con- sistently upwards of 90%. Given that the average average utilization of most other leadership class machines is less (e.g., NSF’s flagship Blue Waters the average utilization fluctuates between 60-80% (see XDMoD[40])) there is ample headroom for similar approaches elsewhere.

**Comment by wellsjc** [comment]
Yes, I agree with this approach.  Thank you.
