### ISSUE TITLE
Conclusion

### ISSUE THREAD

**Issue by shantenujha** [ATLAS-Titan/PanDA-WMS-paper#22]
In shortening the paper, we seem to have removed a mention of Section V (NGE) and its importance / relevance. 

Alessio -- Can you look at Section VII and propose a few sentences, please?

**Comment by AA919** [comment]
Ok, i will do it right now.

AA

**Comment by AA919** [comment]
Added a teeny tiny sentence about NGE at the very end of the paper. I hope it is what you want.

**Comment by shantenujha** [comment]
Thanks.

**Comment by AA919** [comment]
I added a piece about the tests.

**Comment by shantenujha** [comment]
I addressed some of the comments in f3adcb742289cd3e075a415748709fff70f21006  
and 99e7c1f6281ef2b8f8e19febebbce457c4942102
