### ISSUE TITLE
Acknowledgements to ASCR and OLCF

### ISSUE THREAD

**Issue by wellsjc** [ATLAS-Titan/PanDA-WMS-paper#7]
We need to include within an Acknowledgements section an acknowledgement to our (1) ASCR BigPanDA funding, and (2) our use of OLCF resources. 
Here is the formal, suggested OLCF acknowledgement.   It can, of course, be abbreviated.  

"This research used resources of the Oak Ridge Leadership Computing Facility at the Oak Ridge National Laboratory, which is supported by the Office of Science of the U.S. Department of Energy under Contract No. DE-AC05-00OR22725."

**Comment by shantenujha** [comment]
If I understand correctly, due to the double-blinded nature of the review, acknowledgements are not allowed/expected. Matteo -- can you confirm please?

**Comment by wellsjc** [comment]
OK, got it.  This is certainly correct.

Jack

**Comment by mturilli** [comment]
Confirmed.
